version: '3.7'
services:
  client:
    build:
      context: './client'
      dockerfile: Dockerfile
    image: client
    ports:
      - '3000:3000'
    volumes:
      - './client:/app'
    depends_on:
      - server
  server:
    build:
      context: './server'
      dockerfile: Dockerfile
    image: server
    ports:
      - '4000:4000'
    volumes:
      - './server:/app'