import { signIn, useSession } from 'next-auth/react'
import { Kanit } from 'next/font/google'
import Image from 'next/image'

const kanit = Kanit({
  weight: '600',
  subsets: ['latin']
})

const SiginModal = () => {
  const { data } = useSession()
  console.log(data)
  const continueWithGoogle = (e:any) => {
    e.preventDefault()
    signIn('google', {
      callbackUrl: `${window.location.origin}`
    }).catch((err) => {
      console.error('err', err)
    })
  }

  return (
    <div className={`flex flex-col items-center ${kanit.className}`}>
      <Image
        src="/icon/favicon.png"
        width={100}
        height={100}
        alt="logo image"
      />
      <h1 className="text-3xl">Sign in to Nouch</h1>
      <p className="text-gray-400 text-sm mt-1">
        The purpose of this is to verify that upvotes are generated by real
        people. Please note that I do not retain any personal information
      </p>
      <div className="w-full flex flex-col space-y-2 mt-5">
        <div onClick={continueWithGoogle} className="w-full cursor-pointer flex items-center text-white hover:bg-secondary duration-150 border-secondary border-2 rounded-md md:px-9 md:py-3 py-1 md:space-x-3 justify-center">
          <Image
            src="/icon/google.png"
            width={25}
            height={25}
            alt="google image"
          />
          <span>Continue with Google</span>
        </div>
        <div className="w-full cursor-pointer flex items-center text-white hover:bg-secondary duration-150 border-secondary border-2 rounded-md md:px-9 md:py-3 py-1 md:space-x-3 justify-center">
          <Image
            src="/icon/github.png"
            width={25}
            height={25}
            alt="github image"
          />
          <span>Continue with Github</span>
        </div>
      </div>
    </div>
  )
}

export default SiginModal
