name: remote ssh command
on:
  push:
    branches:
      - master
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        command_timeout: 20m
        script: |
          cd nouch.ai/
          git fetch --all
          git reset --hard origin/master
          git pull origin master
          docker stack rm nouch
          docker-compose down --volumes
          docker-compose up -d --build
          docker-compose down --volumes
          docker stack deploy -c docker-compose.yml nouch 
